Merge rules per ingress bt the same host, pathType and backend service
kubernetes-sigs/aws-load-balancer-controller pull request #2986
Opened 2023-01-20 06:43 UTC by oliviassss

### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2203
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2678

### Description

Merged the rules per ingress if:

- they are routing to the same services, and
- they have the same host, and
- they are of the same pathType

#### Tests
- Added unit tests
- Created Ingress with multiple rules, verified that paths were merged only when they have the same host, pathType and backend service. Also verified that when the count of the condition values exceed 5, the merged paths will flow over to a new rule.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-01-24 22:20 UTC, johngmyers requested changes
Is there a big advantage to having a separate code path for unmerged listener rules? It seems like a lot of complexity and I worry about test coverage.

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +				conditions, err := t.buildRuleConditions(ctx, host, paths, enhancedBackend, *currPathType)
Moving this causes any `err` returned from `enhancedBackendBuilder` to be ignored.

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +// func (t *defaultModelBuildTask) buildRuleConditions(ctx context.Context, rule networking.IngressRule,
Edit this commented-out block from the commit

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +			minIdx = algorithm.GetMin(minIdx, currIdx)
The Go way is to just inline this.

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +func (t *defaultModelBuildTask) getRulesToMerge(rules []networking.IngressRule) ([]networking.IngressRule, []networking.IngressRule, error) {
Perhaps name the return values?

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +		}
```
hostToRulesMap[host] = append(hostToRulesMap[host], rule)
```

2023-01-24 22:20 UTC, johngmyers commented on pkg/ingress/model_build_listener_rules.go
> +	var rulesWithReplicateHosts []networking.IngressRule
`rulesWithReplicatedHosts`

2023-05-10 22:41 UTC, closed without merging

2025-10-22 10:46 UTC, omri-shilton commented
@johngmyers This PR might solve a huge issue for us. also solves #2678 
Can we consider merging this?