feat: make webhook failure policy configurable
kubernetes-sigs/aws-load-balancer-controller pull request #3261
Opened 2023-06-28 11:54 UTC by mikutas

### Issue

closes #2711 

### Description

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-07-03 07:23 UTC, johngmyers requested changes
The linked issue #2711 is specific to the PodReadinessGate mutating webhook for Pods. It makes sense to have that webhook fail open, as failing closed can easily cause persistent lack of availability and failing open can only cause an intermittent lack of availability.

This PR, however, creates a single configuration option for the failure policy of all webhooks, not just the PodReadinessGate. Other webhooks, especially the validating ones, are much more critical. So that's a NACK from me.

The Helm chart should just configure the PodReadinessGate mutating webhook to fail open. There is  no need for it to be configurable.

2023-07-03 15:41 UTC, johngmyers commented
Why does this have to be configurable? The chart should just configure `failurePolicy: Ignore`.

2023-07-13 04:10 UTC, johngmyers commented
/ok-to-test
/lgtm
/assign @kishorj

2023-07-21 19:10 UTC, johngmyers commented
/retest

2023-07-23 13:21 UTC, mikutas commented
/retest

2023-07-28 21:47 UTC, johngmyers commented
/retest

2023-07-28 22:46 UTC, johngmyers commented
@mikutas please remove the second commit.

2023-07-29 05:40 UTC, johngmyers commented
/retest

2023-07-29 11:59 UTC, johngmyers commented
/lgtm

2023-08-06 18:32 UTC, johngmyers commented
@mikutas please update the comment at https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/webhooks/core/pod_mutator.go#L46 and run `make crds`.

/lgtm cancel

2023-08-07 02:56 UTC, johngmyers commented
/retest

2023-08-07 02:57 UTC, johngmyers commented
/lgtm

2023-10-26 22:11 UTC, kawai-kobold commented
@johngmyers It looks like the approval label wasn't applied, can you check? We'd love to have this fix in our environment, the webhook failures make most of our GitOps deploys into EKS a real pain.

2024-01-25 01:03 UTC, mikutas commented
/remove-lifecycle stale

2024-04-29 13:53 UTC, kawai-kobold commented
/remove-lifecycle stale

2024-10-21 14:12 UTC, seanturner026 commented
I am truly sorry to be a pest here, but, this is a small PR and was approved previously per the below comment. Is there anything needed to get this out? This issue just caused an outage

https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3261#issuecomment-1667112548

@johngmyers @kishorj @M00nF1sh

2024-10-25 16:01 UTC, seanturner026 commented
Apologies, looks like this is already implemented https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3653

2024-10-27 00:44 UTC, mikutas commented
This issue is about pod mutating webhook
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3653 is about service mutating webhook

2025-02-25 11:50 UTC, mikutas commented
implemented in newer PR #4062 😕

2025-02-25 11:50 UTC, closed without merging