don't block TGB reconciliation loop on failed SG ingress reconciliation
kubernetes-sigs/aws-load-balancer-controller pull request #3296
Opened 2023-07-26 21:05 UTC by michaelsaah

### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3285

### Description

the controller performs an SG reconciliation step for all (cluster-wide) SGs gathered from all TGBs during the TGB reconciliation loop, before TG endpoints are reconciled: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/d177c898ddd86071eecc2fd918d72ebfb0af7892/pkg/targetgroupbinding/resource_manager.go#L139-L141

the way the code is currently written, this means that any failure during SG reconciliation blocks reconciliation of all targets across the whole cluster. such a failure can be caused by something as innocuous as a SG being deleted before the associated TGB is deleted, or a SG being entered on a TGB erroneously. this can easily lead to severe outages if not remediated quickly.

this commit changes the method `reconcileWithIngressPermissionsPerSG` to not exit on a single failed SG ingress reconciliation - instead it will log the offending error and continue through the loop.

I tested this by setting up two TGBs, modifying one to have a non-existent ingress SG, deleting a target pod, then ensuring that the new target is reconciled. the new error message was also logged:
```
{"level":"error","ts":"2023-07-26T19:39:03Z","msg":"Security group reconciliation failed for SG","SecurityGroupID":"sg-0d904125da9f258a7","error":"InvalidGroup.NotFound: The security group 'sg-0b4935e438dcca2ee' does not exist\n\tstatus code: 400, request id: 34e0001c-c85e-4f6e-b7e1-c32093afe402"}```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-07-26 21:52 UTC, johngmyers requested changes
I cannot support what-me-worry ignoring of errors. At the very least, the error needs to be surfaced as a Kubernetes event and the handler needs to mark the work item for retry.

2023-07-26 23:49 UTC, michaelsaah commented
thanks @johngmyers. surfacing the error via an Event sounds fine to me.

I'm not sure what you mean by "mark the work item for retry." can you point me towards any examples in the code where this is performed?

2023-07-28 17:12 UTC, michaelsaah commented
@johngmyers @M00nF1sh just bumping this, it's an ongoing operational issue for us (Twilio) on EKS. any help appreciated.

2023-08-01 17:43 UTC, michaelsaah commented
just another bump, any eyes appreciated

2023-08-04 17:39 UTC, M00nF1sh commented
@michaelsaah 

Thanks for this contribution. I agree with @johngmyers that the error cannot be ignored without retry. Since such SG modification errors can be transient errors such as EC2 api throttle and shall be retried to avoid issues in security group settings.

How about below change:
1. inside reconcileWithIngressPermissionsPerSG, when reconcile for each SG(aggregatedIngressPermissionsPerSG), we don't fail upon error but aggregate all errors into a single error and return it. (e.g. use errors.Join)
2. in https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/d177c898ddd86071eecc2fd918d72ebfb0af7892/pkg/targetgroupbinding/resource_manager.go#L139, if ReconcileForPodEndpoints failed with error, we don't return the error immediately, instead we continue target registration/deregistration and return `runtime.NewRequeueNeeded("networking reconciliation")` if the ReconcileForPodEndpoints returned a error before.

2023-08-04 22:34 UTC, michaelsaah commented
thanks for the review @M00nF1sh, addressed your feedback. have a good weekend!

2023-08-09 21:57 UTC, michaelsaah commented
just bumping this for a re-review, thanks

2023-08-14 16:19 UTC, michaelsaah commented
morning, just a monday review bump, thanks

2023-08-19 23:21 UTC, johngmyers approved these changes
Just a minor style nit

/lgtm

2023-08-19 23:21 UTC, johngmyers commented on pkg/targetgroupbinding/networking_manager.go
> +	sgReconciliationErrors := make([]error, 0)
```suggestion
	var sgReconciliationErrors []error
```

2023-08-19 23:22 UTC, johngmyers commented
/ok-to-test

2023-08-21 17:56 UTC, michaelsaah commented
thanks for the re-review @johngmyers, committed your style suggestion

2023-08-21 18:04 UTC, johngmyers commented
/lgtm
/assign @M00nF1sh

2023-08-21 20:50 UTC, michaelsaah commented
looks like that test might be flaky: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3289#issuecomment-1646227496

2023-08-23 00:10 UTC, johngmyers commented
/retest

2023-08-29 20:05 UTC, M00nF1sh approved these changes
Sorry for late review. This change looks good to me now, thanks a lot for your contribution :D 

/lgtm
/approve

2023-08-29 22:35 UTC, michaelsaah commented
/retest

2023-08-29 23:40 UTC, johngmyers commented
/retest

2023-08-30 00:17 UTC, merged