Add check for LB availability to e2e
kubernetes-sigs/aws-load-balancer-controller pull request #3343
Opened 2023-08-16 21:20 UTC by oliviassss

### Issue

### Description

Add a step to wait for the NLB to be available before proceeding to any resource deletions, to some test suites that were lacking this check. For the below reasons:

- There's a limit from ELB side that if we delete the SG before NLB configuration finishes, it will cause an issue and may put the internal metrics on fire, and ELB is working on adding an error message to this.
- We should check the LB status no matter whether we are doing traffic test or just validating the configurations. 

#### Test:

- Ran the e2e test in my dev cluster and verified all test suites passed.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-08-17 17:26 UTC, oliviassss commented
/retest

2023-08-17 21:50 UTC, oliviassss commented
/retest

2023-08-18 15:27 UTC, johngmyers commented
The suite is timing out. Perhaps the timeout in scripts/run-e2e-test.sh needs to be increased?

2023-08-18 16:31 UTC, oliviassss commented
@johngmyers, thank you! I was just aware that ginkgo v2 change the default timeout from 24h to 1h. I have updated the timeout to 2h, let's see how it works this time.

2023-08-19 22:45 UTC, johngmyers requested changes

2023-08-19 22:45 UTC, johngmyers commented on test/e2e/service/nlb_instance_target_test.go
> +	"strings"
This is an undesirable change. Please format with "goimports"

2023-08-19 23:02 UTC, johngmyers commented on scripts/ci_e2e_test.sh
> +  ginkgo -v -r test/e2e -timeout 2h -- \
```suggestion
  ginkgo -v -r test/e2e --timeout 2h -- \
```

2023-08-21 23:02 UTC, merged