add several doc updates
kubernetes-sigs/aws-load-balancer-controller pull request #3347
Opened 2023-08-17 18:46 UTC by oliviassss

### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3340
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3333
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3259
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3240

### Description
Doc updates for:
- Update legacy provider section with in-tree controller
- Add a pathType note in Ingress Spec
- Update NLB security group section
- Add compatibility matrix of k8s version in helm chart README

Checked the rendering via `make docs-preview`.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-08-18 15:46 UTC, johngmyers requested changes

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/ingress/spec.md
> +        - `pathType: Exact` match are always ordered first
```suggestion
        - `pathType: Exact` paths are always ordered first 
```

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/ingress/spec.md
> +        - followed by `pathType: Prefix` paths with the longest prefix first
```suggestion
        - followed by `pathType: Prefix` paths, with the longest prefix first
```

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/ingress/spec.md
> +        - `pathType: ImplementationSpecific` paths in the order from the manifest
```suggestion
        - followed by `pathType: ImplementationSpecific` paths, in the order they are listed in the manifest
```

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/ingress/spec.md
> +    - However, in case of mixed path types,
The second part of this sentence is redundant with the second list item:

```suggestion
    Beginning from v2.4.3 of the AWS LBC, rules are ordered as follows:
```

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/service/annotations.md
> +  Users can disable this feature and revert to set Cloud Controller Manager (in-tree controller) as the default by setting the helm chart value enableServiceMutatorWebhook to false with `--set enable
```suggestion
  Users can disable this feature and revert to using the AWS Cloud Controller Manager as the default service controller by setting the helm chart `enableServiceMutatorWebhook` value to false with `--set enableServiceMutatorWebhook=false` .
```

2023-08-18 15:46 UTC, johngmyers commented on docs/guide/service/nlb.md
> + - From v2.6.0, the AWS LBC creates and attaches frontend and backend security groups to NLB by default. For more information please check [here](../../deploy/security_groups.md)
```suggestion
 - From v2.6.0, the AWS LBC creates and attaches frontend and backend security groups to NLB by default. For more information please see [the security groups documentation](../../deploy/security_groups.md).
```

2023-08-21 22:40 UTC, oliviassss commented on docs/guide/service/annotations.md
> +  Note that this annotation should be specified during service creation and not edited later. The legacy cloud provider patch was added in Kubernetes v1.20 and is backported to Kubernetes v1.18.18+,
Adapted with minor change.

2023-08-22 01:58 UTC, merged