Revise page on security groups
kubernetes-sigs/aws-load-balancer-controller pull request #3415
Opened 2023-10-02 21:24 UTC by geoffcline

### Description

Revise the description of the security groups page. 

### Checklist
- n/a for docs updates

2023-10-02 21:24 UTC, geoffcline commented
@oliviassss will you review this, please?

2023-10-03 01:12 UTC, geoffcline commented on docs/deploy/security_groups.md
> +- **Specification:** If `--backend-security-group` (default empty) is left empty, an auto-generated security group with the following attributes will be created:
possibly change to "Default Behavior:" or add a heading like previous section.

2023-10-03 01:15 UTC, geoffcline commented on docs/deploy/security_groups.md
> +Backend Security Groups serve as the control mechanism for traffic between AWS Load Balancers and their target EC2 instances or ENIs. A single shared backend security group is utilized to manage the
bring back `This security group is attached to the load balancers and is used as the traffic source in the ENI/Instance security group rules.`

2023-10-03 01:18 UTC, geoffcline commented on docs/deploy/security_groups.md
> -As of version v2.3.0, the controller will by default restrict the backend security group rules to specific port ranges. You can set the controller flag `--disable-restricted-sg-rules` to `true` to ge
link to how to set controller flags?

2023-10-05 04:07 UTC, johngmyers requested changes

2023-10-05 04:07 UTC, johngmyers commented on docs/deploy/security_groups.md
> +- Utilize the controller flag `--disable-restricted-sg-rules` set to `true` to permit traffic to all ports if needed.
```suggestion
- If needed, set the controller flag `--disable-restricted-sg-rules` to `true` to permit traffic to all ports.
```

2023-10-05 04:07 UTC, johngmyers commented on docs/deploy/security_groups.md
> +- **Specification:** Use specific annotations on Ingress or Service resources for specifying frontend security groups, and manage the rules of instance/ENI security groups via additional annotations.
This mangles the section to remove its entire purpose. The point is that specifying the frontend groups will disable LBC's behavior of adding security group rules to the security groups of targets. Furthermore, this behavior can be re-enabled with an annotation, which one depending on whether the resource is Ingress or Service.

2023-10-09 19:11 UTC, geoffcline commented
Thanks for the feedback @johngmyers ! I'm responding and revising now.

2023-10-09 19:16 UTC, geoffcline commented on docs/deploy/security_groups.md
> +- **Frontend Security Groups:** Determine the clients that can access the load balancers.
I am trying a new approach for docs that includes more headings, bullets, use of bold, etc.

2023-10-09 19:28 UTC, geoffcline commented on docs/deploy/security_groups.md
> +- **Backend Security Groups:** Regulate the traffic flowing between load balancers and their associated EC2 instances or ENIs.
I see your point here. I am intentionally including examples of targets. Users really struggle with understanding networking, and want to see network documentation improved. I am unsure if including more examples will help, but I see it as low risk.

2023-10-09 19:30 UTC, geoffcline commented on docs/deploy/security_groups.md
> +Leverage security groups to limit client connections to your load balancers, and tightly define connections with nodes. The AWS Load Balancer Controller defines two classifications of security groups
I changed to "restrict", and will elaborate on this under the backend heading.

2023-10-12 20:26 UTC, closed without merging