feat(NLB): Introduce Service annotation to allow ICMP for Path MTU Discovery
kubernetes-sigs/aws-load-balancer-controller pull request #3939
Opened 2024-11-12 07:24 UTC by chriswachira

### Issue

 #3897 

### Description

It might be necessary for some environments to allow Path MTU discovery for negotiation of MTU between two hosts. If a receiving host has a smaller MTU than the sending host, the receiving host sends an ICMP message to instruct the sending host to split the payload into multiple smaller packets and retransmit them:

- `Destination Unreachable: Fragmentation Needed and Don't Fragment was Set` (Type 3, Code 4) for IPv4 networks.
- `ICMPv6 Packet Too Big (PTB)` (Type 2) for IPv6 networks.

This work introduces a Service annotation (below) that when configured, will automatically add a security group rule to the managed security group, depending on the IP address type.

```
service.beta.kubernetes.io/aws-load-balancer-enable-icmp-for-path-mtu-discovery: "on"
```
&nbsp;

For IPv4 VPCs, an explicit rule is added to the managed security group to allow [ICMPv4 Type 3 Code 4](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-3).

![Screenshot 2024-11-12 at 10 13 27](https://github.com/user-attachments/assets/87781f24-d33d-4d77-8edc-48c73e60a05a)
&nbsp;

For dual stack VPCs, an explicit rule is added to the managed security group to allow both ICMPv4 Type 3 Code 4 and [ICMPv6 Type 2 Code 0](https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml#icmpv6-parameters-codes-2).

<img width="1461" alt="Screenshot 2024-11-12 at 00 40 16" src="https://github.com/user-attachments/assets/33512864-400c-4a6c-b45d-41fd9f9d066f">
&nbsp;

If the `service.beta.kubernetes.io/load-balancer-source-ranges` annotation is also present, it will also create an explicit rule for each source range.

<img width="1461" alt="Screenshot 2024-11-12 at 00 49 22" src="https://github.com/user-attachments/assets/ee2377b7-6c0e-42e4-a3df-59cb44c07bed">

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2024-11-18 18:14 UTC, zac-nixon requested changes

2024-11-18 20:46 UTC, chriswachira commented on docs/guide/service/annotations.md
> +        service.beta.kubernetes.io/aws-load-balancer-enable-icmp-for-path-mtu-discovery: on
I've made this fix, kindly test.

2024-11-18 20:47 UTC, chriswachira commented on pkg/service/model_build_managed_sg.go
> +				if icmpForPathMtuConfigured {
I've added a check to make sure it only adds the security group rules if the annotation value is "on", kindly test.

2024-12-03 22:34 UTC, zac-nixon approved these changes

2024-12-04 19:46 UTC, shraddhabang commented
/ok-to-test

2024-12-07 21:23 UTC, chriswachira commented
/retest

2025-01-21 23:35 UTC, zac-nixon approved these changes

2025-01-21 23:38 UTC, shraddhabang commented
/lgtm
/approve

2025-01-22 00:21 UTC, wweiwei-li approved these changes

2025-01-22 02:18 UTC, merged